services:
  user:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-user.dev
    env_file: .env
    container_name: user
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - coffee-network
  postgres:
      image: postgres:latest
      container_name: postgres
      restart: always
      environment:
      - POSTGRES_DB=coffee
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      ports:
        - "5432:5432"
      networks:
        - coffee-network
networks:
  coffee-network:
