// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/character.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rarity        int32                  `protobuf:"varint,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Vision        string                 `protobuf:"bytes,5,opt,name=vision,proto3" json:"vision,omitempty"`
	WeaponType    string                 `protobuf:"bytes,6,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	Constellation string                 `protobuf:"bytes,7,opt,name=constellation,proto3" json:"constellation,omitempty"`
	Birthday      string                 `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Affilliation  string                 `protobuf:"bytes,9,opt,name=affilliation,proto3" json:"affilliation,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,10,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterMessage) Reset() {
	*x = CharacterMessage{}
	mi := &file_proto_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMessage) ProtoMessage() {}

func (x *CharacterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMessage.ProtoReflect.Descriptor instead.
func (*CharacterMessage) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterMessage) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *CharacterMessage) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CharacterMessage) GetVision() string {
	if x != nil {
		return x.Vision
	}
	return ""
}

func (x *CharacterMessage) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *CharacterMessage) GetConstellation() string {
	if x != nil {
		return x.Constellation
	}
	return ""
}

func (x *CharacterMessage) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *CharacterMessage) GetAffilliation() string {
	if x != nil {
		return x.Affilliation
	}
	return ""
}

func (x *CharacterMessage) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

// Create
type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *CharacterMessage      `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_proto_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCharacterRequest) GetCharacter() *CharacterMessage {
	if x != nil {
		return x.Character
	}
	return nil
}

type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *CharacterMessage      `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_proto_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCharacterResponse) GetCharacter() *CharacterMessage {
	if x != nil {
		return x.Character
	}
	return nil
}

// Update
type UpdateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Character     *CharacterMessage      `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterRequest) Reset() {
	*x = UpdateCharacterRequest{}
	mi := &file_proto_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterRequest) ProtoMessage() {}

func (x *UpdateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCharacterRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCharacterRequest) GetCharacter() *CharacterMessage {
	if x != nil {
		return x.Character
	}
	return nil
}

type UpdateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *CharacterMessage      `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterResponse) Reset() {
	*x = UpdateCharacterResponse{}
	mi := &file_proto_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterResponse) ProtoMessage() {}

func (x *UpdateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterResponse.ProtoReflect.Descriptor instead.
func (*UpdateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCharacterResponse) GetCharacter() *CharacterMessage {
	if x != nil {
		return x.Character
	}
	return nil
}

// Delete
type DeleteCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterRequest) Reset() {
	*x = DeleteCharacterRequest{}
	mi := &file_proto_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterRequest) ProtoMessage() {}

func (x *DeleteCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCharacterRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_proto_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{6}
}

// Get by Name
type GetCharacterByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByNameRequest) Reset() {
	*x = GetCharacterByNameRequest{}
	mi := &file_proto_character_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByNameRequest) ProtoMessage() {}

func (x *GetCharacterByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByNameRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{7}
}

func (x *GetCharacterByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *CharacterMessage      `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterResponse) Reset() {
	*x = GetCharacterResponse{}
	mi := &file_proto_character_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterResponse) ProtoMessage() {}

func (x *GetCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{8}
}

func (x *GetCharacterResponse) GetCharacter() *CharacterMessage {
	if x != nil {
		return x.Character
	}
	return nil
}

// Search
type SearchCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Rarity        int32                  `protobuf:"varint,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Vision        string                 `protobuf:"bytes,4,opt,name=vision,proto3" json:"vision,omitempty"`
	WeaponType    string                 `protobuf:"bytes,5,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCharactersRequest) Reset() {
	*x = SearchCharactersRequest{}
	mi := &file_proto_character_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCharactersRequest) ProtoMessage() {}

func (x *SearchCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCharactersRequest.ProtoReflect.Descriptor instead.
func (*SearchCharactersRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCharactersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchCharactersRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SearchCharactersRequest) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *SearchCharactersRequest) GetVision() string {
	if x != nil {
		return x.Vision
	}
	return ""
}

func (x *SearchCharactersRequest) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

type GetCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*CharacterMessage    `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharactersResponse) Reset() {
	*x = GetCharactersResponse{}
	mi := &file_proto_character_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharactersResponse) ProtoMessage() {}

func (x *GetCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharactersResponse.ProtoReflect.Descriptor instead.
func (*GetCharactersResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_proto_rawDescGZIP(), []int{10}
}

func (x *GetCharactersResponse) GetCharacters() []*CharacterMessage {
	if x != nil {
		return x.Characters
	}
	return nil
}

var File_proto_character_proto protoreflect.FileDescriptor

const file_proto_character_proto_rawDesc = "" +
	"\n" +
	"\x15proto/character.proto\x12\tcharacter\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa8\x02\n" +
	"\x10CharacterMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\x05R\x06rarity\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06vision\x18\x05 \x01(\tR\x06vision\x12\x1f\n" +
	"\vweapon_type\x18\x06 \x01(\tR\n" +
	"weaponType\x12$\n" +
	"\rconstellation\x18\a \x01(\tR\rconstellation\x12\x1a\n" +
	"\bbirthday\x18\b \x01(\tR\bbirthday\x12\"\n" +
	"\faffilliation\x18\t \x01(\tR\faffilliation\x12!\n" +
	"\frelease_date\x18\n" +
	" \x01(\tR\vreleaseDate\"S\n" +
	"\x16CreateCharacterRequest\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.character.CharacterMessageR\tcharacter\"T\n" +
	"\x17CreateCharacterResponse\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.character.CharacterMessageR\tcharacter\"c\n" +
	"\x16UpdateCharacterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x129\n" +
	"\tcharacter\x18\x02 \x01(\v2\x1b.character.CharacterMessageR\tcharacter\"T\n" +
	"\x17UpdateCharacterResponse\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.character.CharacterMessageR\tcharacter\"(\n" +
	"\x16DeleteCharacterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x19\n" +
	"\x17DeleteCharacterResponse\"/\n" +
	"\x19GetCharacterByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Q\n" +
	"\x14GetCharacterResponse\x129\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1b.character.CharacterMessageR\tcharacter\"\x96\x01\n" +
	"\x17SearchCharactersRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\x05R\x06rarity\x12\x16\n" +
	"\x06vision\x18\x04 \x01(\tR\x06vision\x12\x1f\n" +
	"\vweapon_type\x18\x05 \x01(\tR\n" +
	"weaponType\"T\n" +
	"\x15GetCharactersResponse\x12;\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x1b.character.CharacterMessageR\n" +
	"characters2\xe7\b\n" +
	"\x10CharacterService\x12\xdc\x01\n" +
	"\x0fCreateCharacter\x12!.character.CreateCharacterRequest\x1a\".character.CreateCharacterResponse\"\x81\x01\x92A[\n" +
	"\tCharacter\x12\x16Create a new character\x1a6This endpoint allows a user to create a new character.\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/character/create\x12\xc8\x01\n" +
	"\x0fUpdateCharacter\x12!.character.UpdateCharacterRequest\x1a\".character.UpdateCharacterResponse\"n\x92AJ\n" +
	"\tCharacter\x12\x12Update a character\x1a)Updates details of an existing character.\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/character/{id}\x12\xcf\x01\n" +
	"\x0fDeleteCharacter\x12!.character.DeleteCharacterRequest\x1a\".character.DeleteCharacterResponse\"u\x92AT\n" +
	"\tCharacter\x12\x18Delete a character by ID\x1a-Deletes a character based on the provided ID.\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/character/{id}\x12\xda\x01\n" +
	"\x12GetCharacterByName\x12$.character.GetCharacterByNameRequest\x1a\x1f.character.GetCharacterResponse\"}\x92AU\n" +
	"\tCharacter\x12\x17Get a character by name\x1a/Retrieves a character's details using its name.\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/character/name/{name}\x12\xf9\x01\n" +
	"\x10SearchCharacters\x12\".character.SearchCharactersRequest\x1a .character.GetCharactersResponse\"\x9e\x01\x92A{\n" +
	"\tCharacter\x12\x11Search characters\x1a[Search characters using multiple filters like name, region, rarity, vision, or weapon type.\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/character/searchB#Z!github.com/th1enq/go_coffee/protob\x06proto3"

var (
	file_proto_character_proto_rawDescOnce sync.Once
	file_proto_character_proto_rawDescData []byte
)

func file_proto_character_proto_rawDescGZIP() []byte {
	file_proto_character_proto_rawDescOnce.Do(func() {
		file_proto_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_character_proto_rawDesc), len(file_proto_character_proto_rawDesc)))
	})
	return file_proto_character_proto_rawDescData
}

var file_proto_character_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_character_proto_goTypes = []any{
	(*CharacterMessage)(nil),          // 0: character.CharacterMessage
	(*CreateCharacterRequest)(nil),    // 1: character.CreateCharacterRequest
	(*CreateCharacterResponse)(nil),   // 2: character.CreateCharacterResponse
	(*UpdateCharacterRequest)(nil),    // 3: character.UpdateCharacterRequest
	(*UpdateCharacterResponse)(nil),   // 4: character.UpdateCharacterResponse
	(*DeleteCharacterRequest)(nil),    // 5: character.DeleteCharacterRequest
	(*DeleteCharacterResponse)(nil),   // 6: character.DeleteCharacterResponse
	(*GetCharacterByNameRequest)(nil), // 7: character.GetCharacterByNameRequest
	(*GetCharacterResponse)(nil),      // 8: character.GetCharacterResponse
	(*SearchCharactersRequest)(nil),   // 9: character.SearchCharactersRequest
	(*GetCharactersResponse)(nil),     // 10: character.GetCharactersResponse
}
var file_proto_character_proto_depIdxs = []int32{
	0,  // 0: character.CreateCharacterRequest.character:type_name -> character.CharacterMessage
	0,  // 1: character.CreateCharacterResponse.character:type_name -> character.CharacterMessage
	0,  // 2: character.UpdateCharacterRequest.character:type_name -> character.CharacterMessage
	0,  // 3: character.UpdateCharacterResponse.character:type_name -> character.CharacterMessage
	0,  // 4: character.GetCharacterResponse.character:type_name -> character.CharacterMessage
	0,  // 5: character.GetCharactersResponse.characters:type_name -> character.CharacterMessage
	1,  // 6: character.CharacterService.CreateCharacter:input_type -> character.CreateCharacterRequest
	3,  // 7: character.CharacterService.UpdateCharacter:input_type -> character.UpdateCharacterRequest
	5,  // 8: character.CharacterService.DeleteCharacter:input_type -> character.DeleteCharacterRequest
	7,  // 9: character.CharacterService.GetCharacterByName:input_type -> character.GetCharacterByNameRequest
	9,  // 10: character.CharacterService.SearchCharacters:input_type -> character.SearchCharactersRequest
	2,  // 11: character.CharacterService.CreateCharacter:output_type -> character.CreateCharacterResponse
	4,  // 12: character.CharacterService.UpdateCharacter:output_type -> character.UpdateCharacterResponse
	6,  // 13: character.CharacterService.DeleteCharacter:output_type -> character.DeleteCharacterResponse
	8,  // 14: character.CharacterService.GetCharacterByName:output_type -> character.GetCharacterResponse
	10, // 15: character.CharacterService.SearchCharacters:output_type -> character.GetCharactersResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_character_proto_init() }
func file_proto_character_proto_init() {
	if File_proto_character_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_character_proto_rawDesc), len(file_proto_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_character_proto_goTypes,
		DependencyIndexes: file_proto_character_proto_depIdxs,
		MessageInfos:      file_proto_character_proto_msgTypes,
	}.Build()
	File_proto_character_proto = out.File
	file_proto_character_proto_goTypes = nil
	file_proto_character_proto_depIdxs = nil
}
